travis:
  secure:
    BINSTAR_TOKEN: nJIO3avb9pvZopGgAjL2HRhTZEI6NdafHnkAadZf5OU06rj9MC8CW6R9+8xXsOyjQWSxuYoHtu9+GkpLR6O7KgELiZfuuOGxjbWS/O/rNlhe3h/ffYGH3SqbWni67eWsErH/lBpR6U5CutB7t4PIOIbb6fwLOh1YJzaX9/woNfliMVPcDTUuuYnv67UnIerPUZ0NCLEKDZ/zBpxh8g8c/F5yDqpzYvJMyBeL2WE3xlufyeeYMfXFTmld0c8T7BT+6cr35QPfPtKZ2SHdIDrNepUmzMeZRvvpXCLzhxELqduKLB7wPFGJPpBOPdEbi3qnpP3RgTHqae67hj/uVB1f0+votynCzUaAU2ytHG8maqjgN1YlCHLcDquczdBd1l053Dnu+et6uH7odxqx48i5Zi87on8C/Fkkz1LTCuFrb/iGPZrW6L6bqwWfuFtU5FHl6UjKOEWA1JiOBtE7M/Odp/Mr/hWDi5WWvknPynhU8FN1KgJ8B57ZVxAXmjmGILdrYuO5UBoGYncL/XdC3fN6qIuyD6PjWb8814EcPBChXq84G6DL7zwwx0oX0GGyh2DQevMMTurGU0hRBSWRZQeJRHP3YAWxA5ZLISesxVLUVvKKWg5ndqLjhRubv+3y6SGEXaEJilQ9cECdrCxn8wNb3IIlhht9LXjxDB8pS+FcmZo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
